### ISSUE TITLE
Lunch

### ISSUE THREAD

**Issue by a-pasquale** [nodeschool/western-mass#15]
Looking at Holyoke Hummus Company to provide lunch.

http://www.holyokehummuscompany.com/menu

Thoughts?

**Comment by Sequoia** [comment]
- [ ] Call RVM
- [ ] ??

**Comment by Sequoia** [comment]
@a-pasquale can you dedupe the list & get tentative headcount? Plz assign me back w/that.

**Comment by a-pasquale** [comment]
Have you heard back from vendors? We need to arrange delivery also.

**Comment by Sequoia** [comment]
I'm working with dam, I need to hear back from rvm but I've called them

**Comment by Sequoia** [comment]
### Pay
- [ ] Small Oven
- [ ] Dunkin
- [ ] RVM
- [ ] Delivery

**Comment by Chuck39** [comment]
Huh? Are we supposed to vote? If so, we need more info.....

**Comment by Sequoia** [comment]
@Chuck39 sorry! this is an "organizing" ticket, plz ignore :)

**Comment by Chuck39** [comment]
OK... Carry on :)
