### ISSUE TITLE
Sponsor ❤️

### ISSUE THREAD

**Issue by Sequoia** [nodeschool/western-mass#17]
* Tweet (from @ nerds I suppose?)
* Let them know their logos are up & they're getting value.

**Comment by Sequoia** [comment]
@a-pasquale what's status on this? https://twitter.com/NERDSummit it doesn't look like any have gone out as of yet. Is there a buffer account attached to nerdsummit? If so we can queue some tweets to go out over the week.

**Comment by a-pasquale** [comment]
Done.
