### ISSUE TITLE
Childcare

### ISSUE THREAD

**Issue by Sequoia** [nodeschool/western-mass#21]
Sounds like we have a vendor & a quote, we need to figure out when they need final numbers by (but with 2 childcare people we will probably be fine).

Other considerations: space. @a-pasquale let us know if you hear fro MHPCC about this.

**Comment by a-pasquale** [comment]
I have talked with MGHPCC and Lauren about space at the computer center. We can support up to 10 kids from ages 6-10. Less if there are younger kids who would like to come.

Can we mention childcare in a pre-event email in case there are any others who would like to bring kids?

**Comment by Sequoia** [comment]
Yes. Currently I think we only have 1 signup & he's iffy, so it may just be
my kids (??). If it's down to just my kids.... idk, I am kind of relying on
the childcare to be honest. :)

Are we finalized with the childcare vendor?

-Sequoia

**Comment by a-pasquale** [comment]
We are all set with the childcare vendor.  She will arrive early (7ish) on Saturday to setup. Another staff member will cover the first couple hours and then she will return for the remainder of the day. She will contact parents of kids who registered interest. We can still have more kids, so we should advertise the option more widely.
