### ISSUE TITLE
Slides: Promises & Streams

### ISSUE THREAD

**Issue by Sequoia** [nodeschool/western-mass#24]
- [ ] deck
- [ ] talk

**Comment by Sequoia** [comment]
done such as they are :sweat_smile:

**Comment by chadfurman** [comment]
Out of curiosity, is all of this such in here somewhere that we might peruse before the adventure tomorrow?

**Comment by Sequoia** [comment]
Yep! https://docs.google.com/presentation/d/1QoAOomGy874ULTIBxkoIBf_N47TeTpotsGVTB3YeQzk/edit?usp=docslist_api

I'll tell you what my public speaking teacher told me however: **the slides are not your presentation, they support your presentation.** As such, don't expect them to be a fully stand-alone document :smile:

**Comment by Chuck39** [comment]
Check slides 11 & 12 - overwritten text.

**Comment by Sequoia** [comment]
Ha, yeah. Play the transitions 😁

Thanks for the check, let me know if you find anything else!
