### ISSUE TITLE
Carpooling

### ISSUE THREAD

**Issue by swinggraphics** [nodeschool/western-mass#28]
I feel dirty using an "issue" to make this request, but Sequoia recommended it: Is anyone coming from or through Northampton I could get a ride with?

**Comment by ghost** [comment]
I'm traveling from Goshen so will be going through Northampton, but am only attending the morning session. If you are interested let me know.

**Comment by swinggraphics** [comment]
Thanks, I'd love a ride! There isn't a way to message privately on Github. Can you connect with me on Facebook https://www.facebook.com/gregperham or email onetime@swinggraphics.com?
